Dev 34 encode
python52course/one-time-secret-api pull request #11
Opened 2024-08-11 13:15 UTC by RomanPecheritsa

2024-08-12 07:45 UTC, ApriCotBrain commented on onetimesecret/main.py
> +import os
Если хочется писать красивый код, то стоит обращать внимание на штуки, типа форматирования, корректность импортов и т.п.. Здесь импорты можно поправить.
Сначала должны идти импорты из стандартной библиотеки, потом из установленных библиотек, потом из пакетов/файлов проекта. Если импортируется несколько функций/методов, то в алфавитном порядке. 
Есть линтер isort, который подскажет как правильно.

2024-08-12 07:45 UTC, ApriCotBrain commented on onetimesecret/main.py
> +    raise ValueError("MASTER_KEY not found in environment variables.")
я бы здесь дефолтное значение задала, вместо условия. Но это субъективно

2024-08-12 07:45 UTC, ApriCotBrain commented on onetimesecret/main.py
>      return JSONResponse(content={"secret_key": secret_key})
насколько знаю, в проектах fastapi в эндпоинтах должно быть минимум логики, ее всю выносят в репозитории, или другие слои. Тут послушала бы, что более опытный Илья скажет:-)

2024-08-12 07:45 UTC, ApriCotBrain commented on onetimesecret/utils.py
> +    """
докстринги лайк:-) очень классно когда они содержательные. при командной разработке - полезное:-)

2024-08-13 15:39 UTC, RomanPecheritsa commented on onetimesecret/main.py
> +    raise ValueError("MASTER_KEY not found in environment variables.")
Далее идет перевод из str в byte
MASTER_KEY = master_key_str.encode('utf-8'), 
поэтому думаю, что лучше так оставить

2024-08-13 16:14 UTC, kaziamov requested changes

2024-08-13 16:14 UTC, kaziamov commented on onetimesecret/main.py
>      while True:
Можно ли переписать это решение без while?

2024-08-13 16:14 UTC, kaziamov commented on onetimesecret/utils.py
> +    kdf = PBKDF2HMAC(
Что такое kdf?

2024-08-13 16:17 UTC, RomanPecheritsa commented on onetimesecret/main.py
> +import os
+

2024-08-13 16:21 UTC, RomanPecheritsa commented on onetimesecret/utils.py
> +    kdf = PBKDF2HMAC(
Key Derivation Function. Переменная которая содержит класс PBKDF2HMAC

2024-08-13 16:22 UTC, RomanPecheritsa commented on onetimesecret/main.py
>      while True:
Если использовать uuid. Но этот пароль будет возвращаться пользователю для доступа ко второму эндпоинту, поэтому его необходимо делать проще. Подумаю как можно по другомк реализовать

2024-08-14 08:34 UTC, RomanPecheritsa commented on onetimesecret/main.py
>      return JSONResponse(content={"secret_key": secret_key})
Реализую вывод в отдельный слой

2024-08-14 10:56 UTC, RomanPecheritsa commented
Внес изменения по выявленным недостаткам

2024-08-15 16:06 UTC, kaziamov requested changes

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/main.py
> +    except InvalidPassphraseException:
Нужно убрать ошибки

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/main.py
> +    except Exception as e:
Убрать ошибку

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/main.py
>  @app.post("/generate", response_model=str)
Попробовать добавить роутеры

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/services.py
> +class InvalidSecretKeyException(Exception):
Перенести в отдельный модуль exceptions

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/services.py
> +            raise InvalidSecretKeyException
Заменить на возврат пустого значения

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/services.py
> +            raise InvalidPassphraseException
Заменить на возврат пустого значения

2024-08-15 16:06 UTC, kaziamov commented on tests/test_main.py
> +    assert retrieve_response.status_code == 404
Нужно сделать отдельные тест кейсы на каждый кейс

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/services.py
> +
Нужно запустить линтер

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/services.py
> +        master_key_str = os.getenv("MASTER_KEY")
Нужно чтобы данные передавались снаружи

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/services.py
> +        self.repository = FakeRepository()
Все зависимости должны передавать снаружи, а не создаваться внутри

2024-08-15 16:06 UTC, kaziamov commented on onetimesecret/services.py
> +    async def generate_secret(self, request: SecretRequest) -> str:
Должны передавать только те данные, которые нужны работы бизнес логики

2024-08-18 20:52 UTC, RomanPecheritsa commented on onetimesecret/services.py
> +            raise InvalidSecretKeyException
Далее идет декодирование секрета, выкинет ошибку, создам исключение подниму его выше

2024-08-20 07:05 UTC, ApriCotBrain approved these changes

2024-08-20 07:05 UTC, ApriCotBrain commented on onetimesecret/routes.py
> +@route.post("/secrets/{secret_key}", response_model=str)
насколько я знаю, response_model это именно про модель

2024-08-20 14:34 UTC, hagp55 approved these changes

2024-08-20 14:34 UTC, hagp55 commented on onetimesecret/routes.py
> +@route.post("/secrets/{secret_key}", response_model=str)
Может имя параметра request переименовать, у тебя экземпляр твой Pydantic модели, немного запутывает, зачем ты отдаешь JsonResponse если можно просто вернуть словарь и по дефолту будет JSONResponse?

2024-08-20 19:43 UTC, svereshagin approved these changes
Nicely done!

2024-08-20 19:44 UTC, svereshagin commented
Gg

2024-08-21 15:54 UTC, RomanPecheritsa commented on onetimesecret/routes.py
> +@route.post("/secrets/{secret_key}", response_model=str)
Со всем согласен, сейчас поправлю

2024-08-21 15:55 UTC, RomanPecheritsa commented on onetimesecret/main.py
> +    except InvalidPassphraseException:
+

2024-08-22 07:41 UTC, kaziamov requested changes

2024-08-22 07:41 UTC, kaziamov commented on tests/test_database.py
>  import pytest
нет тестов на кейсы 

1. при повторном обращении к секрету, который был считан
2. при повторном запросе на создание кейс
3. негативные кейсы на чтение с неподходящими данными
4. тесты на секреты с ttl

2024-08-22 09:46 UTC, kaziamov approved these changes

2024-08-22 09:50 UTC, merged