DEV-19 init repository, add gitignore, add poetry files, add project …
python52course/one-time-secret-api pull request #4
Opened 2024-07-25 09:45 UTC by RomanPecheritsa

…structure, install libraries

2024-07-25 09:56 UTC, kaziamov requested changes

2024-07-25 09:56 UTC, kaziamov commented on main.py
Файл выше директории с кодом не нужен. Для запуска кода нужно сделать модуль внутри onetimesecret

2024-07-25 09:56 UTC, kaziamov commented on pyproject.toml
> +description = ""
Нужно добавить описание на англ

2024-07-25 09:56 UTC, kaziamov commented on .gitignore
> +#.idea/
Можно раскомментировать эту строку и добавить директорию .vscode

2024-07-25 16:24 UTC, ApriCotBrain commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/python
https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file
я бы добавила пустую строку в конце файла

2024-07-25 17:47 UTC, ApriCotBrain approved these changes

2024-07-26 05:31 UTC, FuneralKitty approved these changes
Good

2024-07-27 20:09 UTC, kaziamov approved these changes

2024-07-27 20:24 UTC, merged