DEV-20-create_fake_db
python52course/one-time-secret-api pull request #5
Opened 2024-07-26 07:00 UTC by RomanPecheritsa

2024-07-27 20:12 UTC, kaziamov requested changes

2024-07-27 20:12 UTC, kaziamov commented on onetimesecret/database.py
> +secrets_db: List[Dict[str, str]] = []
Использовать словари для передачи данных плохая практика, , либо передавать явно какие поля передаются или использовать пайдантик модели

2024-07-27 20:13 UTC, kaziamov commented
Не забывай запрашивать ревью других людей в поле справа, так они получат уведомление, о том, что от них ждут ревью

2024-07-28 06:49 UTC, ApriCotBrain reviewed
Предлагаю дублировать пул-реквесты на ревью в соответствующем треде в телеграм.

2024-07-28 10:38 UTC, kaziamov requested changes

2024-07-28 10:38 UTC, kaziamov commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/python
Обнови ветку сделав слияние, git merge dev в текущую ветку. Так в пулреквесте останутся только файлы, которые относятся к этой задаче

2024-07-28 13:35 UTC, RomanPecheritsa commented on onetimesecret/database.py
> +secrets_db: List[Dict[str, str]] = []
Фейковая БД нужна для того чтобы имитировать работу реальной. MongoDB планирую добавлять в проект на последнем этапе. Сейчас же secrtes_db список словарей, будет выполнять функцию сохранения словаря (документ БД), получение словаря и удаление. Модели которые будут работать с данными БД реализуются на следующих этапах

2024-07-28 15:40 UTC, kaziamov approved these changes

2024-07-28 17:59 UTC, merged