DEV-32-endpoint-generate
python52course/one-time-secret-api pull request #8
Opened 2024-07-30 12:02 UTC by RomanPecheritsa

2024-07-30 12:14 UTC, kaziamov requested changes

2024-07-30 12:14 UTC, kaziamov commented on onetimesecret/main.py
> +        JSONResponse: A JSON response containing the generated secret_key.
Используй тип возвращаемого значения в сигнатуре функции

2024-07-30 12:14 UTC, kaziamov commented on tests/test_main.py
> +async def test_generate_secret_success(clear_repository):
Нужно добавить тесты на ситуации, когда секретный ключ пытаются считать дважны или он не существует

2024-07-30 12:14 UTC, kaziamov commented on onetimesecret/models.py
> +
Пройдсь линтером, форматирование немного неверное

2024-07-30 12:14 UTC, kaziamov commented on onetimesecret/utils.py
> +    selection = ascii_letters + digits
возможно стоит вынести наружу, так как это переиспользуется. чтобы не тратить ресурсы на склейку строк при каждом запросе к функции

2024-07-30 12:14 UTC, kaziamov commented on tests/test_utils.py
> +def test_generate_secret_key_length():
Добавить негативные кейсы, для ситуаций, когда код работает не как должен, например, если длина больше 6, что должно произойти

2024-07-30 12:14 UTC, kaziamov commented on tests/test_utils.py
> +def test_generate_secret_key_uniqueness():
Что будет если ключ не уникальный, как поведет себя прилоежние?

2024-08-01 18:32 UTC, RomanPecheritsa commented on tests/test_utils.py
> +def test_generate_secret_key_uniqueness():
Добавлена логика, если ключ для доступа к секрету уже есть в базе будет сформирован новый

2024-08-01 18:35 UTC, RomanPecheritsa commented on onetimesecret/main.py
> +        JSONResponse: A JSON response containing the generated secret_key.
Исправлено

2024-08-01 18:36 UTC, RomanPecheritsa commented on onetimesecret/models.py
> +
Выполнено

2024-08-01 19:15 UTC, kaziamov approved these changes

2024-08-01 19:33 UTC, merged